DATA_DIR = 'data'
APPROVED_FILE_EXTENSIONS = ['.txt']
BLACKLIST = ['doesn', 'cant', 'isnt', 'arent']
LENGTH_THRESHOLD = 3
SIZE_THRESHOLD = 5
MAX_ITERATIONS = 50
NUM_REVIEWED_SENTENCES = 5
NUM_LEARNED_SENTENCES = 10
